	# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
	
	#               this file processes linear mixed model (LMM) data generated by SAS and calculates the mean window period.
	#               NB this variant of the script keeps OD constant and varies the number of samples, S.
	#               mean windows are stored in the "mean" list, ie mean[[j]], where j corresponds to index in "names" array.
	
	# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
	
	# settings
	fileReadLocation = "C:/Documents and Settings/heastwood/My Documents/SACEMA/OD cut-off/harg-22-10/"
	OD <- 0.8 #OD remains fixed when varying Scut
	ODL <- 0.0476     #ODL remains fixed when varying Scut
	fileFixedArray <- "LMM_var_S_const_OD0.8_TL.0_TU.140_+_COV1.out"
	fileRandomArray <- "LMM_SAS_OUT_rand_var_S_const_OD0.8_TL.0_TU.140_+_COV1"


	# <-------------------------------------------------Functions ----------------------------------------------------------------------------------------->

	# boot strap
		bootMean <- function (data=window.elk[,3],B=1000,alpha=c(0.025,0.975)) {
		library(bootstrap)
		n <- length(data)
		theta <- mean(data)
		boot.theta <- numeric(B)
		for(i in 1:B){
			boot.data <- data[sample(1:n,replace=TRUE)]
			boot.theta[i] <- mean(boot.data)
		}
				
		#BCa
		BCa <-bcanon(data,nboot=B,theta=function(x)mean(x),alpha=alpha)$confpoint[,2]
		leng.BCa <- max(BCa)-min(BCa)
		vorm.BCa <- (max(BCa)-theta)/(theta-min(BCa))
		
			
		#lower, upper, bootmean, mean
		return (c(BCa[1], BCa[2],mean(boot.theta),theta))
	}


	# <-------------------------------------------------End functions ----------------------------------------------------------------------------------------->

	
	# <-------------------------------------------------Code ----------------------------------------------------------------------------------------->
	
	# Open names or values file

	#create different OD cutof scenarios and store in list
	Sdata <- list(); surv <- list(); avg <- list(); mean <- list(); var <- list(); CI <- list(); sasOut <- list(); upper <- list(); lower <- list();
	colours = c("red","blue","green","yellow","black","purple", "cyan","magenta", "orange", "pink", "brown", "violet")
	limitArray = array(); uTemp = array(); lTemp = array();CIout = array()
	fixedArray <- read.table(file = paste(fileReadLocation, fileFixedArray, sep=""), head=TRUE, sep=",")
	namesArray <- read.table(file = paste(fileReadLocation, fileRandomArray, ".names", sep=""), head=FALSE, sep=",")
	
	loopStart <- 1
	loopLimit <- dim(fixedArray)[1]
	for (j in c(loopStart:loopLimit)) {
		sasOut[[j]] <- read.table(file = paste(fileReadLocation, fileRandomArray,".S", namesArray$V1[j], ".csv", sep=""), head=TRUE, sep=",")
		k <- 1
		l <- 1
		len <- dim(sasOut[[j]])[1]
		uTemp = array(); lTemp = array();
		while (k < len) {
			uTemp[l] = exp((sqrt(OD)- fixedArray[j,1] - sasOut[[j]][k,3])/(fixedArray[j,2] + sasOut[[j]][k+1,3]))
			lTemp[l] = exp((sqrt(ODL)- fixedArray[j,1] - sasOut[[j]][k,3])/(fixedArray[j,2] + sasOut[[j]][k+1,3]))
			k <- k + 2
			l <- l + 1
		}
					print(paste(fixedArray[j,1], fixedArray[j,2]))
		lower[[j]] <- lTemp
		upper[[j]] <- uTemp
		mean[[j]] <- mean(uTemp - lTemp)
		CI[[j]] <- bootMean(uTemp - lTemp)
		CIout[j] <- paste(namesArray$V1[j], CI[[j]][3], (CI[[j]][3] - CI[[j]][1]), ((CI[[j]][2] - CI[[j]][3])), sep=" ")
	}
	
	#write mean and CI to csv file
	write.table(CIout, file = paste(fileReadLocation, fileRandomArray,".mean.csv", sep=""), sep = " ", col.names = FALSE, append="FALSE", row.names=FALSE, quote=FALSE)
	
	
	# <-------------------------------------------------End code ----------------------------------------------------------------------------------------->
