		# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
		
		#               this file processes linear mixed model (LMM) data generated by SAS and calculates the mean window period.
		#               NB this variant of the script keeps OD constant and varies the cut off time in which OD is considered.
		#               means are stored in "mean" list, ie mean[[j]], where j corresponds to index in "names" array.
		
		# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
		
		# settings
		fileReadLocation = "C:/Documents and Settings/heastwood/My Documents/SACEMA/OD cut-off/harg-22-10/"
		
		# ------------ For Varying OD in LMM mean calculation -------------
		cutStart <- 0.2
		cutStop <- 1.6
		cutStep <- 0.2
		# ------------------------------------------------------------------
		
		ODL <- 0.0476 # for the LMM equation
		
		CfixedArray =     c(-1.9366,  -2.1400, -2.1600,   -2.1970, -2.2433,  -2.2492,  -2.2408, -2.1081) 
		SlopeFixedArray = c( 0.5016,   0.5467,   0.5582,   0.5695,  0.5833,   0.5893,   0.5940,  0.5763)
		names = c("0.2", "0.4", "0.6", "0.8", "1.0", "1.2", "1.4", "1.6")
		
		
		# <-------------------------------------------------Functions ----------------------------------------------------------------------------------------->
	
		# boot strap
		bootMean <- function (data=window.elk[,3],B=1000,alpha=c(0.025,0.975)) {
		library(bootstrap)
		n <- length(data)
		theta <- mean(data)
		boot.theta <- numeric(B)
		for(i in 1:B){
			boot.data <- data[sample(1:n,replace=TRUE)]
			boot.theta[i] <- mean(boot.data)
		}
				
		#BCa
		BCa <-bcanon(data,nboot=B,theta=function(x)mean(x),alpha=alpha)$confpoint[,2]
		leng.BCa <- max(BCa)-min(BCa)
		vorm.BCa <- (max(BCa)-theta)/(theta-min(BCa))
		
			
		#lower, upper, bootmean, mean
		return (c(BCa[1], BCa[2],mean(boot.theta),theta))
	}
	
	
		# <-------------------------------------------------End functions ----------------------------------------------------------------------------------------->
	
		
		# <-------------------------------------------------Code ----------------------------------------------------------------------------------------->
		ODcut = cutStart
		loopLimit = ((cutStop - cutStart)/cutStep) + 1
		#create different OD cutof scenarios and store in list
		Sdata <- list(); surv <- list(); avg <- list(); mean <- list(); var <- list(); CI <- list(); sasOut <- list(); upper <- list(); lower <- list();
		limitArray = array(); uTemp = array(); lTemp = array();
		for (j in c(1:loopLimit)) {
			sasOut[[j]] <- read.table(file = paste(fileReadLocation, "SAS-rand-OD.", names[j], ".csv", sep=""), head=TRUE, sep=",")
			k <- 1
			l <- 1
			len <- dim(sasOut[[j]])[1]/8
			while (k < len) {
				uTemp[l] = exp((sqrt(ODcut)- CfixedArray[j] - sasOut[[j]][k,3])/(SlopeFixedArray[j] + sasOut[[j]][k+1,3]))
				lTemp[l] = exp((sqrt(ODL)- CfixedArray[j] - sasOut[[j]][k,3])/(SlopeFixedArray[j] + sasOut[[j]][k+1,3]))
				k <- k + 2
				l <- l + 1
			}
			lower[[j]] <- lTemp
			upper[[j]] <- uTemp
			mean[[j]] <- mean(uTemp - lTemp)
			CI[[j]] <- bootMean(uTemp - lTemp)
			ODcut = ODcut + cutStep
		}
		
		
		# <-------------------------------------------------End code ----------------------------------------------------------------------------------------->
