	# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
	
	#               this file processes linear mixed model (LMM) data generated by SAS and calculates the mean window period.
	#               NB this variant of the script keeps OD constant and varies the cut off time in which OD is considered.
	#               means are stored in "mean" list, ie mean[[j]], where j corresponds to index in "names" array.
	
	# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
	
	# settings
	fileReadLocation = "C:/Documents and Settings/heastwood/My Documents/SACEMA/OD cut-off/harg-22-10/"
	loopStart <- 1
	loopLimit <- 3
	OD <- 0.8
	ODL <- 0.0476
	
	CfixedArray =     c( -1.3154,  -1.3933, -1.5212)#,  -1.5433, -1.5250, -1.5615,  -1.5668,  -1.5832,   -1.5832,  -1.6078,  -1.6078, -1.6078, -1.6078, -1.6657, -1.6657, -1.6657, -1.6525, -1.9095)
	SlopeFixedArray = c( 0.4283,  0.4447,  0.4685)#,   0.4700,  0.4610,  0.4649,   0.4642,   0.4668,    0.4668,   0.4701,   0.4701,  0.4701,  0.4701,  0.4799,  0.4799,  0.4799,  0.4751,  0.5178)
	names <-          c("t60",     "t70",   "t80")#,    "t90",   "t100",  "t110",  "t120",   "t130",    "t140",   "t150",   "t160",  "t170",  "t180",  "t190",  "t200",  "t240",  "t400", "tall")
	
	
	# <-------------------------------------------------Functions ----------------------------------------------------------------------------------------->

	# boot strap
	bootMean <- function (data=window.elk[,3],B=1000,alpha=c(0.025,0.975)) {
		library(bootstrap)
		n <- length(data)
		theta <- mean(data)
		boot.theta <- numeric(B)
		for(i in 1:B){
			boot.data <- data[sample(1:n,replace=TRUE)]
			boot.theta[i] <- mean(boot.data)
		}
				
		#BCa
		BCa <-bcanon(data,nboot=B,theta=function(x)mean(x),alpha=alpha)$confpoint[,2]
		leng.BCa <- max(BCa)-min(BCa)
		vorm.BCa <- (max(BCa)-theta)/(theta-min(BCa))
		
			
		#lower, upper, bootmean, mean
		return (c(BCa[1], BCa[2],mean(boot.theta),theta))
	}


	# <-------------------------------------------------End functions ----------------------------------------------------------------------------------------->


	# <-------------------------------------------------Code ----------------------------------------------------------------------------------------->
	
	#create different OD cutof scenarios and store in list
	Sdata <- list(); surv <- list(); avg <- list(); mean <- list(); var <- list(); CI <- list(); sasOut <- list(); upper <- list(); lower <- list();
	limit <- 0.3
	colours = c("red","blue","green","yellow","black","purple", "cyan","magenta", "orange", "pink", "brown", "violet")
	limitArray = array(); uTemp = array(); lTemp = array();
	for (j in c(loopStart:loopLimit)) {
		sasOut[[j]] <- read.table(file = paste(fileReadLocation, "var_Tcut_const_S2+COV1.", names[j], ".csv", sep=""), head=TRUE, sep=" ")
		k <- 1
		l <- 1
		len <- dim(sasOut[[j]])[1]
		while (k < len) {
			uTemp[l] = exp((sqrt(OD)- CfixedArray[j] - sasOut[[j]][k,3])/(SlopeFixedArray[j] + sasOut[[j]][k+1,3]))
			lTemp[l] = exp((sqrt(ODL)- CfixedArray[j] - sasOut[[j]][k,3])/(SlopeFixedArray[j] + sasOut[[j]][k+1,3]))
			k <- k + 2
			l <- l + 1
		}
		lower[[j]] <- lTemp
		upper[[j]] <- uTemp
		mean[[j]] <- mean(uTemp - lTemp)
		CI[[j]] <- bootMean(uTemp - lTemp)
	}
	
	
	# <-------------------------------------------------End code ----------------------------------------------------------------------------------------->
